version: 1

# Connection
git_protocol: ssh
http_unix_socket:

# UI
editor: codium --reuse-window --wait --
pager: delta
spinner: enabled
color_labels: enabled
accessible_colors: disabled
accessible_prompter: disabled

# Behavior
prompt: enabled
prefer_editor_prompt: disabled
browser:
aliases: {}

# Telemetry
telemetry: disabled
