# macOS: ~/Library/Application Support/tlrc/config.toml (tlrc ignores XDG on Darwin)
# Linux: ~/.config/tlrc/config.toml

[cache]
auto_update = true
defer_auto_update = false
languages = ["en"]

[output]
show_title = true
platform_title = true
option_style = "both"
show_hyphens = true
compact = true
